  # Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Antonio Cucciniello
email: antonio.cucciniello16@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey there! I am Antonio and I like to build cool things with software,
  read books on self-help and entrepreneurship, and interested in
  living a healthy life.  If you are interested in any of those 
  things you are in the right place!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.acucciniello.com" # the base hostname & protocol for your site
twitter_username: antocucciniello
github_username:  acucciniello
youtube_url: https://www.youtube.com/channel/UC8icMMql5SjCaXXMvILGIUA

# Build settings
markdown: kramdown
theme: minima
